@extends('layout.v_template')
@section('title', 'Hiden Paradise Hunter | About')

@section('content')
<header class="masthead" style="background-image: url('gambar/kubu1.jpg')">
    <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="site-heading">
        <h2>ABOUT</h2>
        <h2>KARANGASEM DESTINATIONS</h2>
    <img src="{{ asset('gambar/kubu1.jpg') }}" class="loginimg mw-100 img-fluid" alt="Responsive image">
    <div class="card-body">
    <p>Karangasem merupakan kabupaten yang terletak di ujung paling timur Pulau Bali. Secara astronomis, kabupaten ini berada pada posisi 8°00'00"–8°41'37,8" Lintang Selatan dan 115°35'9,8"–115°54'8,9" Bujur Timur. Luas wilayah Kabupaten Karangasem adalah 839,54 km² atau 83.954 Ha yang terdiri atas 8 Kecamatan, 75 desa, dan 3 kelurahan. Kecamatan-kecamatan di Kabupaten Karangasem meliputi: Kecamatan Rendang, Sidemen, Manggis, Karangasem, Abang, Bebandem, Selat, dan Kubu. <br><br>
        Sejarah Karangasem tidak lepas dengan sejarah berdirinya Kerajaan Karangasem.

        Nama Karangasem sebenarnya berasal dari kata Karang Semadi. Beberapa catatan yang memuat asal-muasal nama karangasem adalah seperti yang diungkapkan dalam Prasasti Sading C yang terdapat di Geria Mandara, Munggu, Badung. Lebih lanjut diungkapkan bahwa Gunung Lempuyang di timur laut Amlapura, pada mulanya bernama Adri Karang yang berarti Gunung Karang.

        Dalam penelitian sejarah keberadaan pura, Lempuyang dihubungkan dengan kata lampu yang artinya terpilih, dan Hyang yang berarti Tuhan (Bathara Guru, Hyang Parameswara). Di Adri Karang inilah Hyang Agnijaya membuat Pura Lempuyang Luhur sebagai tempat bersemadi (Karang Semadi). Lambat laun nama Karang Semadi ini berubah menjadi Karangasem. <br><br>

        Secara geologi Kabupaten Karangasem terdiri dari formasi Kuarter, Kuarter Bawah, dan Miosin. Formasi Kuarter meliputi sebagian besar wilayah kabupaten. Formasi Kuarter dengan Litologi Tufa Pasiran dan endapan lahar terdapat di pesisir utara yakni di daerah Tianyar. Litologi berupa lahar, pasir, lapili diarahkan bom, warna coklat tua hingga hitam. Sebarannya di daerah Gunung Agung, Selat, Muncan, sepanjang aliran Tukad Buhu, dan Tukad Bangka. Di Belahan utara mulai dari daerah Gunung Agung, wilayah Kecamatan Kubu, sebagian Kecamatan Abang, daerah aliran sungai Unda. Komposisi lahar terdiri dari batuan beku andesit dan batu apung dengan masa dasar tufa pasiran. Pasir komposisinya terdiri dari faalspar, gelas vulkanik, dan mineral hitam. Lapili dan bom komposisinya terdiri dari batu apung dan lava andesit, umumnya batuan ini belum mengeras dan mudah lepas. Setempat-setempat pada batuan ini terdapat lava dan breksi, kompak dan keras, pada lava sebagian berongga. Formasi Kuarter Bawah terdapat di daerah ujung timur kabupaten yakni Kecamatan Karangasem bagian timur dan Kecamatan Abang bagian utara. Litologinya berupa lava dan breksi Gunung Api Seraya. Lava berwarna abu-abu kehitaman. Breksi berwarna coklat. Formasi Miosin terdapat di perbukitan Kecamatan Manggis dan Selat. Litologinya berupa breksi dan lava merupakan formasi Ulakan. Lava berwarna abu-abu kehitaman dan breksi berwarna coklat kehitaman.

        Jenis tanah yang terdapat di Kabupaten Karangasem berupa jenis mediteran, alluvial, latosol, dan regosol. Jenis tanah mediteran merupakan bagian terkecil (147 ha atau 0,2%), sebarannya di bagian pesisir kecamatan Manggis seperti sebagian wilayah Desa Antiga, wilayah Desa Ulakan, wilayah Desa Manggis, wilayah Nyuh Tebel (Kecamatan Karangasem). Jenis tanah alluvial tersebar di Kecamatan Sidemen, Manggis, Karangasem, Bebandem dan Selat. Kemudian latosol (luas 36.325 ha atau 43,3%) di wilayah Kecamatan Karangasem bagian timur (Desa Seraya, Seraya Barat, Seraya Timur), sebagian wilayah Kecamatan Abang seperti Desa Purwakerti, daerah perbukitan Manggis sampai sebagian Kecamatan Selat bagian selatan, dan sebagian Kecamatan Sidemen. Jenis tanah latosol ini umumnya sangat rawan terhadap erosi, lebih-lebih di Kecamatan Karangasem Timur karena tanahnya banyak terdiri dari batu lepas dengan vegetasi yang kurang serta kemiringan yang terjal. Jenis tanah regosol (luas 36.784 ha atau 43,8%) meliputi sebagian terbesar wilayah Kabupaten Karangasem. Sebarannya adalah dari bagian utara sampai bagian tengah. Tanah jenis ini juga rawan erosi khususnya pada daerah dengan kemiringan lahan tinggi. <br><br>

        Suhu udara di wilayah Kabupaten Karangasem sangat beragam oleh karena faktor ketinggian suatu tempat, tetapi pada umumnya suhu udara rata-rata di wilayah Karangasem berkisar antara 20°–32 °C, tetapi untuk suhu udara di wilayah perbukitan dan pegunungan biasanya kurang dari 20 °C. Tingkat kelembapan nisbi di wilayah ini pun bervariasi antara 76%–81%. Berdasarkan klasifikasi iklim Koppen, sebagian besar wilayah Kabupaten Karangasem beriklim tropis basah dan kering (Aw) dengan dua musim, yaitu musim kemarau dan musim penghujan. Musim kemarau di wilayah Karangasem biasanya berlangsung pada periode Mei–Oktober dengan bulan terkering adalah Agustus dan September dengan curah hujan bulanan di bawah 20 mm per bulan. Sementara itu, musim penghujan di Kabupaten Karangasem berlangsung pada periode November–April dengan bulan terbasah Januari dan Februari yang curah hujan bulanannya di atas 200 mm per bulan. Curah hujan tahunan di wilayah Kabupaten Karangasem berkisar antara 1.000–1.700 mm per tahun dengan jumlah curah hujan berkisar antara 90–140 hari hujan per tahun. <br>
    </p>
</div>
</header>
@endsection